development: &defaults
  adapter: postgresql
  host: localhost
  database: resonanz_development
  encoding: unicode
  pool: 5
  username: postgres
  password:

test:
  <<: *defaults
  database: resonanz_test

production:
  database: resonanz_production

